source "https://rubygems.org"

gem 'rainbow', '~> 2.1.0'
gem 'rspec', '~> 3.5.0'
gem 'rake', '~> 12.0'
gem 'rubocop', '~> 0.46.0'
gem 'sinatra', '~> 2.0'
gem 'sinatra-activerecord', '~> 2.0'
gem 'sqlite3', '~> 1.3.13'
